import { STATUS_TYPES } from "@/utils/constants";

export const API_CATEGORIES = '/categories';
export const API_FILES = '/files';
export const API_FILES_UPLOAD_CONFIG = `${API_FILES}/upload-config`;
export const API_FILES_COMPLETE = `${API_FILES}/complete`;
export const API_HSN = '/hsn';
export const API_PRODUCTS = '/products';
export const API_PRODUCTS_NOTIFY = (id) => `${API_PRODUCTS}/${id}/notify-me`;
export const API_PRODUCT_REVIEWS = (id) => `${API_PRODUCTS}/${id}/reviews`;
export const API_PRODUCT_REVIEW_ME = (id) => `${API_PRODUCTS}/${id}/reviews/me`;
export const API_PRODUCT_REVIEW_SELF = (reviewId) => `${API_PRODUCTS}/reviews/${reviewId}/me`;
export const API_PRODUCT_REVIEWS_ADMIN = (id) => `${API_PRODUCTS}/${id}/reviews/admin`;
export const API_PRODUCT_REVIEW_VISIBILITY = (reviewId) => `${API_PRODUCTS}/reviews/${reviewId}/visibility`;
export const API_SIZE = '/sizes';
export const API_COLOR = '/colors';
export const API_AUTH = '/auth';
export const API_REGISTER = `${API_AUTH}/register`;
export const API_RESET_PASSWORD = `${API_AUTH}/reset-password`;
export const API_LOGIN = `${API_AUTH}/login`;
export const API_LOGIN_WITH_OTP = `${API_AUTH}/login-with-otp`;
export const API_VERIFY_OTP = `${API_AUTH}/verifyOTP`;
export const API_VERIFY_GOOGLE_TOKEN = `${API_AUTH}/verifyGoogleToken`;
export const API_USERS = '/users';
export const API_USERS_ROLE = `${API_USERS}/role`;
export const API_USER_INFO = '/users/getUserInfo';
export const API_USER_UPDATE_PROFILE = '/users/updateProfile';
export const API_ADDRESS = '/address';
export const API_ORDERS = '/orders';
export const API_ORDER_DISPUTE = (slug) => `${API_ORDERS}/${slug}/dispute`;
export const GET_ACTIVE_API = (API, params) => (params?.status === STATUS_TYPES.ACTIVE) ? `${API}/active` : API ; 
export const API_ADMIN_ORDERS = `${API_ORDERS}/admin`
export const API_PAYMENT_VERIFY = `${API_ORDERS}/payment/verify`;
export const API_CONFIG = '/config';
export const API_CART = '/cart';
export const API_WISHLIST = '/wishlist';
export const API_DASHBOARD = '/dashboard';
export const API_AUDIT_LOGS = '/audit-logs';
export const API_AUDIT_LOGS_STATS = `${API_AUDIT_LOGS}/stats`;
