
export const FEATURE_TYPES = {
    USER: 'USER',
    CATEGORY: 'CATEGORY',
    PRODUCT: 'PRODUCT'
};

export const STATUS_TYPES = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE'
};

export const ROLE_TYPES = {
    USER: 'USER',
    ADMIN: 'ADMIN'
}

export const OTP_TYPES = {
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    RESET_PASSWORD: 'RESET_PASSWORD'
}

export const STOCK_TYPES = {
    PRODUCT: 'PRODUCT',
    ORDER: 'ORDER',
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    WITHDRAW: 'WITHDRAW'
}

export const SQL_VALUE_CONFIG = {
    PAYMENT_PENDING_TIME: '5 minutes'
}

export const ERR_CODES = {
    STOCK_CHANGED: "STOCK_CHANGED",
    ORDER_VALIDATION: "ORDER_VALIDATION" 
}

export const PAYMENT_TYPES = {
    ONLINE: 'ONLINE',
    COD: 'COD'
}

export const ORDER_STATUS = {
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    PLACED: 'PLACED',
    CONFIRMED: 'CONFIRMED',
    REJECTED: 'REJECTED',
    SHIPPED: 'SHIPPED',
    CANCELLED: 'CANCELLED',
    DELIVERED: 'DELIVERED'
}

export const ORDER_STATUS_NEXT_STEPS = {
    [ORDER_STATUS.PAYMENT_PENDING]: [],
    [ORDER_STATUS.PLACED]: [
        ORDER_STATUS.CONFIRMED,
        ORDER_STATUS.REJECTED
    ],
    [ORDER_STATUS.CONFIRMED]: [
        ORDER_STATUS.SHIPPED
    ],
    [ORDER_STATUS.SHIPPED]: [
        ORDER_STATUS.DELIVERED
    ],
    [ORDER_STATUS.DELIVERED]: [],
    [ORDER_STATUS.CANCELLED]: [],
    [ORDER_STATUS.REJECTED]: []
}

export function getNextOrderStatuses(currentStatus) {
    return ORDER_STATUS_NEXT_STEPS[currentStatus] || [];
}

export const CONFIG_KEYS = {
    SHIPPING: 'SHIPPING',
    COMP_INFO: 'COMP_INFO',
    COURIER: 'COURIER'
}
